# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a4b89866-9c96-4459-9633-020204c6f2ba";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/653b84a5-003c-4f76-a4d0-68e0be823ca3"; }
    ];

  nix.maxJobs = 4;
}
